# Generated by Django 5.2.7 on 2025-11-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='lab_report',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
